In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
import os

In [7]:
os.path.expanduser('~/Users/phinchosherpa/Desktop/nyu/BirdVox-DCASE-20k_csv-private.csv')
csv_path='/Users/phinchosherpa/Desktop/nyu/BirdVox-DCASE-20k_csv-private.csv'

In [8]:
df=pd.read_csv(csv_path)

In [9]:
df.head()

,Unit,Item start (s),Has bird,#Calls,UUID,Call timestamps (s)
0,unit01,0.100,0,0,857f7bac-58da-4d6c-a0c5-82bbdc7c518e,[]
1,unit01,12.598,0,0,1eacd200-b03d-4089-a6ae-8b9a95f06739,[]
2,unit01,22.698,0,0,9f8b9739-40a6-439f-aa22-caa42f9758ee,[]
3,unit01,35.196,0,0,f65c9917-f852-478f-aad0-dd91b720679e,[]
4,unit01,45.296,0,0,e7b31cd3-b2d3-4d01-af95-91f9ea27e856,[]

In [10]:
calls=df["#Calls"]

In [11]:
df[df["#Calls"]==6]

,Unit,Item start (s),Has bird,#Calls,UUID,Call timestamps (s)
1542,unit01,17423.158,1,6,bf5b8ad6-6d41-473c-ae0c-7af639b8a886,"['1.896', '2.747', '3.206', '3.746', '6.712', ..."
1845,unit01,20847.954,1,6,b4749ac9-dcff-4082-a251-2233c3d20cef,"['1.599', '3.388', '5.719', '6.363', '7.881', ..."
2220,unit01,25083.880,1,6,f64a8d47-bd3f-4e3a-a5cc-0731d8f4f2cf,"['1.062', '1.767', '3.764', '5.206', '6.553', ..."
2803,unit01,31672.396,1,6,52774ca0-bfde-42e8-ad26-d46d734d4035,"['0.864', '2.044', '3.647', '6.939', '7.354', ..."
3187,unit01,36011.212,1,6,c04414e8-3924-4c23-adb1-6f3b4adac379,"['0.188', '1.020', '2.708', '5.164', '6.334', ..."
3311,unit01,37412.288,1,6,20a793c1-9024-42d4-a3bf-de11a71063dc,"['1.652', '2.607', '2.830', '4.376', '7.464', ..."
3347,unit01,37819.052,1,6,4af6e187-457d-4229-a8b8-426013c3cafc,"['3.330', '4.071', '6.945', '7.117', '8.189', ..."
3351,unit01,37864.248,1,6,0967e8f2-50d7-4dc9-a424-36f9dff8708f,"['2.732', '4.102', '5.132', '6.007', '6.457', ..."
3352,unit01,37874.348,1,6,daa63daf-19bd-4545-a644-b4b87fb43389,"['1.493', '1.842', '4.237', '4.728', '5.239', ..."
3358,unit01,37942.142,1,6,7a0e2152-1ed4-4a9f-a951-0cc518b85721,"['1.914', '3.240', '4.819', '8.297', '8.694', ..."
3394,unit01,38348.906,1,6,83dfd673-50d0-4c3f-a840-d5b6f99cbbe5,"['1.028', '4.504', '4.818', '5.747', '6.980', ..."
3395,unit01,38361.404,1,6,1c4c5c56-58fd-48f1-a092-2a2da7e90b11,"['1.113', '1.507', '1.713', '3.961', '6.756', ..."
3400,unit01,38416.700,1,6,9762ea4b-93e6-48e5-a90a-39c728a13413,"['1.199', '1.353', '2.617', '7.781', '8.116', ..."
3401,unit01,38429.198,1,6,a00f65a7-654f-4f23-a5f4-badd5547db31,"['1.249', '1.476', '5.070', '5.372', '6.976', ..."
3404,unit01,38461.896,1,6,4ed8ac90-8fc2-40cb-a0e3-1cc711f78af4,"['0.094', '3.959', '5.877', '7.238', '8.229', ..."
3684,unit02,2362.790,1,6,753dfc2b-2d4b-4b09-ae6c-1a37f6cca88b,"['0.799', '2.511', '4.160', '6.384', '7.849', ..."
5353,unit02,21219.622,1,6,35106347-2330-4d42-acd9-7ce8f6ef2681,"['0.171', '3.271', '3.579', '5.314', '7.766', ..."
5561,unit02,23569.814,1,6,4b917e02-17f9-4ca8-a6a9-b63399569f94,"['1.247', '3.824', '5.741', '6.844', '8.409', ..."
5945,unit02,27908.630,1,6,415a0a52-d99f-4eb2-ad68-f19d2afefc95,"['0.902', '1.694', '6.619', '6.998', '7.395', ..."
6230,unit02,31130.044,1,6,85d6db8a-f0fe-4cc3-a596-eb63c13efc34,"['5.282', '6.184', '7.073', '8.184', '9.120', ..."
6232,unit02,31152.642,1,6,95782ddd-c0f2-4dc0-a66b-c4f5676e5704,"['0.559', '1.734', '2.258', '3.118', '4.192', ..."
6709,unit02,36541.066,1,6,3163d3d4-d899-4c81-ab23-5304cb47bae3,"['0.573', '1.759', '3.749', '7.424', '7.587', ..."
6747,unit02,36970.428,1,6,117741f2-167d-4a81-a6fe-a64f3f1374c7,"['4.341', '6.290', '6.784', '7.507', '9.748', ..."
6749,unit02,36993.026,1,6,b4efcf02-3f77-4631-aa98-ddce34dd99e4,"['0.246', '0.618', '1.702', '5.170', '8.528', ..."
6771,unit02,37241.604,1,6,8d299686-2ba8-4445-add1-765521729384,"['3.790', '4.564', '6.437', '7.389', '7.972', ..."
6777,unit02,37309.398,1,6,f61110e4-d279-48a2-a4fb-1613d0005b87,"['0.002', '1.018', '1.166', '2.540', '7.067', ..."
6819,unit02,37783.956,1,6,a785dced-13d7-4195-af77-f5e31b721b1e,"['2.815', '5.311', '5.922', '8.255', '8.398', ..."
6829,unit02,37896.946,1,6,6678e908-275f-4ffa-adfb-39eaddb85c73,"['0.052', '0.501', '2.862', '5.592', '5.705', ..."
6830,unit02,37909.444,1,6,b147d3f8-c3fb-4671-ab79-5f126bbea9f0,"['0.777', '1.520', '3.255', '3.414', '8.674', ..."
6831,unit02,37919.544,1,6,91b6f13c-5aa8-4162-a04e-8c17b30ea9ca,"['0.080', '3.596', '6.900', '7.065', '8.596', ..."
...,...,...,...,...,...,...
17599,unit10,2340.192,1,6,3af59de5-8b46-4458-a57a-064fbfae04af,"['1.164', '3.375', '3.489', '8.922', '9.218', ..."
17644,unit10,2847.448,1,6,192f56c9-8d96-487e-a3f0-28801bb33c4d,"['1.810', '3.124', '7.365', '7.931', '8.401', ..."
17698,unit10,3457.594,1,6,3db077f6-8e36-41cc-a412-d8ed23f85bbb,"['3.835', '7.323', '8.078', '8.322', '8.446', ..."
18068,unit10,7638.224,1,6,3cb65eac-04d7-457b-a3ec-05c22705cdb8,"['0.819', '3.048', '5.284', '6.536', '7.949', ..."
18306,unit10,10327.386,1,6,754faf73-613d-413a-a889-b660f9d6671d,"['0.494', '3.268', '4.971', '7.012', '8.846', ..."
18324,unit10,10530.768,1,6,7717b131-6e65-4091-a6e7-f3b55c236f6f,"['1.263', '3.319', '5.447', '6.217', '7.691', ..."
18617,unit10,13842.574,1,6,a5242995-f093-4f27-a79f-44ac25528b0e,"['3.364', '3.423', '4.576', '5.649', '7.458', ..."
18679,unit10,14543.112,1,6,a98ca5fb-f02e-4abb-a677-4434fd792045,"['0.145', '0.967', '5.194', '6.651', '7.575', ..."
18779,unit10,15673.012,1,6,9f99959f-05b0-463d-a0ed-62baa45482cd,"['0.212', '0.370', '6.084', '7.547', '9.238', ..."
18921,unit10,17277.470,1,6,fc8eb440-dfd7-414d-ad48-93c4c6e17c78,"['0.056', '1.469', '5.717', '6.506', '6.738', ..."
19002,unit10,18191.490,1,6,1e8d27fe-8b7f-4b65-abf8-29a500672579,"['0.548', '1.939', '4.342', '4.793', '6.642', ..."
19047,unit10,18701.144,1,6,858b38ad-3e73-4a7d-a155-07e4e8a5ed8c,"['2.191', '3.177', '3.811', '4.544', '7.410', ..."
19079,unit10,19062.712,1,6,dc799a35-15cd-423e-aa7b-c8f06912d4bd,"['0.453', '1.268', '2.324', '4.522', '7.791', ..."
19084,unit10,19118.008,1,6,ca1ad0b8-dfa3-4d77-a9df-a04d0df78e5d,"['0.079', '0.917', '2.221', '5.743', '6.940', ..."
19131,unit10,19650.260,1,6,d37506ab-70a2-42d7-a99a-0393d44d2f94,"['3.142', '5.075', '7.193', '7.848', '8.464', ..."
19161,unit10,19989.230,1,6,f5dd1ed8-8517-4111-a4ce-4dcfbc744905,"['1.289', '3.568', '5.392', '7.303', '9.001', ..."
19271,unit10,21232.120,1,6,b308e4f1-c3d6-4e41-afb0-2d4994ae5777,"['1.926', '6.172', '6.429', '9.221', '9.403', ..."
19273,unit10,21254.718,1,6,99496d21-f7c7-4938-a87f-43e44e6f6757,"['0.157', '0.395', '3.327', '3.490', '3.812', ..."
19364,unit10,22281.728,1,6,15b5193f-7237-44df-ac2c-5f213882c077,"['2.456', '2.994', '3.083', '5.554', '7.332', ..."
19379,unit10,22452.412,1,6,2eecf3c5-829f-4639-abec-bda825f4f9ed,"['4.599', '4.942', '6.761', '7.753', '8.554', ..."
19485,unit10,23650.106,1,6,622c040b-6056-470d-ab4f-f4c955e294cc,"['0.032', '2.196', '3.622', '3.953', '7.963', ..."
19543,unit10,24305.448,1,6,a16f80bd-ef5a-4bcb-aa65-78fbec4e0c95,"['0.958', '1.858', '5.185', '7.078', '7.248', ..."
19615,unit10,25118.976,1,6,e081b8ca-c3e5-478c-a87f-76f4d6009372,"['1.864', '3.460', '4.072', '7.696', '8.652', ..."
19637,unit10,25367.554,1,6,792232a4-7b5d-4e7d-a02b-36d2f9a8b01d,"['1.306', '3.574', '5.269', '6.311', '8.438', ..."
19702,unit10,26100.790,1,6,5210888b-6978-49dd-aa8a-2c5912c17168,"['0.293', '3.151', '3.159', '4.228', '5.208', ..."
19729,unit10,26407.062,1,6,93007ce1-160b-4a72-aae1-a74aea68ccb5,"['0.125', '1.164', '3.702', '7.809', '7.948', ..."
19859,unit10,27875.932,1,6,478c3800-50f0-456f-a0ea-f273d4bfcbbb,"['2.665', '2.919', '3.055', '4.774', '4.855', ..."
19860,unit10,27886.032,1,6,55f0011b-9450-4cdc-a197-7ecd881ca2ee,"['4.476', '6.338', '6.576', '7.046', '8.658', ..."
19885,unit10,28169.706,1,6,c4b0ad2c-e1fa-49eb-ad5b-c3552f32d4ca,"['0.768', '2.058', '3.986', '6.659', '7.596', ..."
19976,unit10,29196.716,1,6,9f90c85f-f3c4-4253-ac41-2afc17f698ac,"['0.003', '2.517', '5.200', '5.652', '7.998', ..."

In [12]:
counter = Counter(calls)

print(counter)

Counter({0: 10072, 1: 4248, 2: 2408, 3: 1285, 4: 720, 5: 383, 6: 210, 7: 109, 8: 75, 9: 69, 10: 42, 14: 29, 13: 24, 12: 21, 16: 18, 11: 17, 19: 15, 17: 15, 15: 14, 20: 14, 30: 14, 23: 14, 24: 13, 22: 12, 35: 11, 18: 10, 25: 9, 21: 8, 27: 7, 31: 7, 29: 7, 28: 7, 37: 7, 32: 6, 43: 6, 26: 5, 34: 5, 36: 5, 41: 5, 45: 5, 33: 4, 40: 4, 51: 4, 46: 4, 54: 3, 39: 3, 38: 3, 42: 3, 49: 3, 50: 3, 47: 3, 44: 2, 59: 1, 68: 1, 58: 1, 67: 1, 60: 1, 64: 1, 48: 1, 53: 1, 55: 1, 76: 1})

In [13]:
df[df["#Calls"]==15]

,Unit,Item start (s),Has bird,#Calls,UUID,Call timestamps (s)
3392,unit01,38326.308,1,15,75c48cb9-a464-49c7-a867-e719d60d0970,"['0.484', '1.089', '1.970', '2.934', '3.409', ..."
3421,unit01,38655.178,1,15,024a895c-e99d-4699-adb9-538cda9ea48c,"['0.037', '0.493', '0.547', '0.897', '1.179', ..."
6231,unit02,31140.144,1,15,eacb53a8-2af3-48b8-ae46-2a9284cfa2d6,"['0.612', '1.070', '1.684', '2.875', '2.969', ..."
6865,unit02,38303.710,1,15,87355dfe-8b31-4fc3-a9ef-48f4eb6a4829,"['0.159', '1.082', '2.028', '2.467', '2.958', ..."
6941,unit02,39162.434,1,15,7081588a-5e42-4a15-a9ce-9369ee5bb6b5,"['0.158', '1.445', '2.385', '2.954', '5.915', ..."
10308,unit03,37919.544,1,15,727f6ae9-1a46-4d47-a14b-e5c8ea60e043,"['0.899', '1.158', '1.220', '1.964', '2.187', ..."
10408,unit03,39049.444,1,15,213e4c6a-8b4b-4bd5-a210-2bc373830173,"['0.007', '1.492', '1.624', '1.861', '2.426', ..."
10412,unit03,39094.640,1,15,46448bb5-1f22-4288-addf-4545ce42301c,"['0.058', '0.518', '2.266', '3.240', '4.510', ..."
13883,unit05,38971.550,1,15,2c2c0e97-e047-43b3-a88f-c41d80e227f5,"['0.895', '1.091', '1.949', '2.120', '2.813', ..."
13892,unit05,39072.042,1,15,0c7707b0-8088-42e1-a50b-f918757198bd,"['0.589', '1.214', '1.389', '1.503', '1.936', ..."
17322,unit07,38484.494,1,15,62d05dbd-9236-4b39-a534-8c1b9fdf8655,"['1.467', '1.615', '2.114', '2.353', '2.601', ..."
17346,unit07,38755.670,1,15,4070d431-37c9-4d22-a77b-712b02c8f3c1,"['0.308', '0.890', '1.785', '2.029', '2.285', ..."
19886,unit10,28179.806,1,15,33fda6fc-df01-46e6-aa26-55635411c7b5,"['0.253', '2.887', '3.119', '3.268', '4.198', ..."
19965,unit10,29073.626,1,15,c1e75473-b5bf-44a6-a57e-6adcded6f2c8,"['0.272', '1.589', '2.276', '2.384', '3.488', ..."